version: "3.8"
services:
  web-app:
    image: webapp
    ports:
      - "8080:80"
    environment:
      - ENV=$WEB_APP_ENV
      - APP_TITLE=Opex Exchange
      - DESCRIPTION=A decentralized cryptocurrency exchange
      - API_BASE_URL=http://10.2.6.25:8094
      - CLIENT_ID=web-app
      - LOGIN_CLIENT_ID=web-app
      - CLIENT_SECRET=08b82acc-e437-4095-8bcb-b9c98076bdeb
      - PRELOAD_LANG=$PRELOAD_LANG
      - LANGS_SUPPORT=$LANGS_SUPPORT
      - DEFAULT_THEME=$DEFAULT_THEME
      - REGISTER_EMAIL_ADDRESS=$REGISTER_EMAIL_ADDRESS
      - REFERENCE_FIAT_CURRENCY=$WEB_APP_REFERENCE_FIAT_CURRENCY
      - CALENDAR_TYPE=$WEB_APP_CALENDAR_TYPE
      - MOBILE_URL=$WEB_APP_MOBILE_URL
    networks:
      - default
    deploy:
      restart_policy:
        condition: on-failure
networks:
  default:
    driver: bridge